//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopilotChat.WebApi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CopilotChat.WebApi.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating token usage.
        /// </summary>
        internal static string CalculateTokenUsage {
            get {
                return ResourceManager.GetString("CalculateTokenUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting user intent.
        /// </summary>
        internal static string ExtractUserIntent {
            get {
                return ResourceManager.GetString("ExtractUserIntent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating bot response.
        /// </summary>
        internal static string GenerateBotResponse {
            get {
                return ResourceManager.GetString("GenerateBotResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No relevant data was returned from the index.
        /// </summary>
        internal static string NoRelevantData {
            get {
                return ResourceManager.GetString("NoRelevantData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying the search index.
        /// </summary>
        internal static string QuerySearchIndex {
            get {
                return ResourceManager.GetString("QuerySearchIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving message to chat history.
        /// </summary>
        internal static string SaveMessageChatHistory {
            get {
                return ResourceManager.GetString("SaveMessageChatHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving user message to chat history.
        /// </summary>
        internal static string SaveUserMessageChatHistory {
            get {
                return ResourceManager.GetString("SaveUserMessageChatHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate a query based on the input.
        /// </summary>
        internal static string UnableGenerateQuery {
            get {
                return ResourceManager.GetString("UnableGenerateQuery", resourceCulture);
            }
        }
    }
}
