@rootUrl=http://localhost:7134
@modelId=PurchaseOrder
@fileName=purchaseOrderThree.pdf

GET  {{rootUrl}}/api/GetModels

### 

GET {{rootUrl}}/api/GetModelById?modelId={{modelId}}

###

DELETE  {{rootUrl}}/api/DeleteModel?modelId={{modelId}}


###

POST {{rootUrl}}/api/AnalyzeModel
Content-Type: application/json

{
    "values": [
        {
            "recordId": "1",
            "data": {
              "metadata_storage_name": "{{fileName}}"
            }
        }
    ]
    
}